#!/bin/sh

SUM=`md5sum /etc/crontab`
CONTENT=`cat ~/.md5cron`

if [ ! -f ~/.md5cron ]
then
	md5sum /etc/crontab > ~/.md5cron
	exit 0
fi

if [ "$SUM" != "$CONTENT" ]
then
	md5sum /etc/crontab > ~/.md5cron
	echo "/etc/crontab has been modified!"
	echo "/etc/crontab has been modified!" | sudo mail root
fi
